project_name: flac
env:
  - GO111MODULE=on
  # - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod tidy

build:
  binary: flac
  id: flac
  main: ./cmd/flac
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  goarm:
    - 7

archives:
- id: "flac"
  builds: ['flac']
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
    - README.md
    - LICENSE

checksum:
  name_template: '{{.ProjectName}}_v{{.Version}}_checksums.txt'
snapshot:
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
